### ISSUE TITLE
 host='127.0.0.1',是否支持域名格式?

### ISSUE THREAD

**Issue by feng99** [anjia0532/lua-resty-redis-util#13]
host='127.0.0.1',
但是从阿里云购买的redis连接地址这样的格式
r-8vbv28pt8yxxxxx.redis.zhangbei.rds.aliyuncs.com

请问是否支持?

**Comment by anjia0532** [comment]
没做限制，理论上支持。

**Comment by feng99** [comment]
搞明白了  和lua无关  是nginx的限制  修改nginx.conf增加一行resolver 8.8.8.8即可.
