### ISSUE TITLE
确定new()方法默认配置能行？

### ISSUE THREAD

**Issue by finday3** [anjia0532/lua-resty-redis-util#4]
```
  if (type(opts) ~= "table") then
    return nil, "user_config must be a table"
  end
```

**Comment by anjia0532** [comment]
感谢指出，已更正。
https://github.com/anjia0532/lua-resty-redis-util/blob/96eae69935d3f86ae118e919f9f98da5c2bd2ca1/lib/resty/redis-util.lua#L262-L266
