### ISSUE TITLE
new 函数的 and not path 不太理解，还是bug

### ISSUE THREAD

**Issue by zhenzhenyang** [anjia0532/lua-resty-redis-util#5]
![ukpln _ q11s p 6 fdvq0r](https://user-images.githubusercontent.com/5217888/46067275-07d78a00-c1a9-11e8-9c07-dea09322921b.png)

**Comment by anjia0532** [comment]
https://github.com/anjia0532/lua-resty-redis-util/blob/0ed6cb46a98bd5c2cc081a36116779a4a086cfb8/lib/resty/redis-util.lua#L308-L310

这个path是遗留参数，忘记删了，不过，不影响逻辑啊，path本身就没值，所以后边表达式恒等于true，如果host和port没值，属于确实必填参数，直接return，后边我会去掉path的
