### ISSUE TITLE
timeout参数代码里怎么没用到？

### ISSUE THREAD

**Issue by baober90** [anjia0532/lua-resty-redis-util#6]
_connect_mod函数connect之前怎么没设置超时时间

**Comment by anjia0532** [comment]
https://github.com/anjia0532/lua-resty-redis-util/blob/0ed6cb46a98bd5c2cc081a36116779a4a086cfb8/lib/resty/redis-util.lua#L295-L299
赋值给 keepalive  了

**Comment by hirryli** [comment]
timeout为什么不生效呢
