### ISSUE TITLE
两点疑问

### ISSUE THREAD

**Issue by askiter** [anjia0532/lua-resty-redis-util#7]
line  107
  local ok, err = _connect_mod(self,redis)
我看了一下 _connect_mode() 的定义，虽然在形参里面引入了self，但是实际上相关的连接参数如host和post之类，都是以全局变量的模式引入的，这些参数是在_M.new()方法中进行的赋值处理。so，这里的self应该是不需要的

Line  308  
  if not (host and port) and not path then
    return nil, "no redis server configured. \"host\"/\"port\" is required."
  end
请问这里的 path 是做什么用的，目前没有看到有任何地方引用

谢谢

**Comment by anjia0532** [comment]
关于`self`,是为了`:`调用,自行百度 `lua . : 区别`

关于全局变量。。。`local`修饰的是局部变量

关于 `path` 重复 #5 ,冗余的，一直没删。
