### ISSUE TITLE
attempt to concatenate global 'port' (a nil value)

### ISSUE THREAD

**Issue by aceslup** [anjia0532/lua-resty-redis-util#9]
> 2019/05/27 14:51:32 [error] 30132#30132: *19482 lua entry thread aborted: runtime error: /usr/local/nginx/lua/video_count.lua:29: attempt to concatenate global 'port' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/nginx/lua/video_count.lua:29: in function </usr/local/nginx/lua/video_count.lua:1>, client: 11.22.33.44, server: _, request: "GET /video/20190408/20190409170029898.mp4 HTTP/1.1", host: "abc.com"

大神，为何会出现port值为nil呢。看代码，没赋值默认是6379呢。

**Comment by anjia0532** [comment]
video_count.lua:29 贴一下代码看看
